export type { IPatientCommunication } from './IPatientCommunication';
export type { IPatientContact } from './IPatientContact';
export type { IPatientLink } from './IPatientLink';
export type { IPersonLink } from './IPersonLink';
export type { IPractitionerQualification } from './IPractitionerQualification';
export type { IRelatedPersonCommunication } from './IRelatedPersonCommunication';
export type { IPractitionerRoleAvailableTime } from './IPractitionerRoleAvailableTime';
export type { IPractitionerRoleNotAvailable } from './IPractitionerRoleNotAvailable';
export type { IOrganizationContact } from './IOrganizationContact';
