import { ResourceValidator } from './validators/ResourceValidator';
import { IResourceValidatorProperties } from './GlobalResourceTypes';
import {
  Address,
  Availability,
  Attachment,
  CodeableConcept,
  CodeableReference,
  ExtendedContactDetail,
  Coding,
  VirtualServiceDetail,
  ContactPoint,
  Duration,
  Extension,
  HumanName,
  Identifier,
  Meta,
  Period,
  Quantity,
  Range,
  Reference,
  SimpleQuantity,
  Signature,
} from '../r5/models/datatypes';
import {
  Bundle,
  Endpoint,
  Group,
  Location,
  Organization,
  Patient,
  Person,
  Practitioner,
  PractitionerRole,
  RelatedPerson,
} from '../r5/models/resources';
import {
  BundleLink,
  BundleEntrySearch,
  BundleEntryResponse,
  BundleEntryRequest,
  BundleEntry,
  EndpointPayload,
  GroupCharacteristic,
  GroupMember,
  LocationPosition,
  PatientCommunication,
  PatientContact,
  PatientLink,
  PersonLink,
  PersonCommunication,
  PractitionerQualification,
  PractitionerCommunication,
  RelatedPersonCommunication,
  OrganizationQualification,
} from '../r5/models/backbones';

export class FhirContextR5 {
  getInstances() {
    return {
      Address,
      Availability,
      Attachment,
      CodeableConcept,
      CodeableReference,
      ExtendedContactDetail,
      Coding,
      ContactPoint,
      Duration,
      Extension,
      HumanName,
      Identifier,
      Meta,
      Period,
      Quantity,
      Range,
      Reference,
      SimpleQuantity,
      Signature,
      VirtualServiceDetail,
      Bundle,
      BundleEntry,
      BundleEntryRequest,
      BundleEntryResponse,
      BundleEntrySearch,
      BundleLink,
      Endpoint,
      EndpointPayload,
      Group,
      GroupMember,
      GroupCharacteristic,
      Location,
      LocationPosition,
      Organization,
      OrganizationQualification,
      Patient,
      PatientCommunication,
      PatientContact,
      PatientLink,
      Person,
      PersonLink,
      PersonCommunication,
      Practitioner,
      PractitionerQualification,
      PractitionerCommunication,
      PractitionerRole,
      RelatedPerson,
      RelatedPersonCommunication,
    };
  }
  public getValidator(): IResourceValidatorProperties {
    return {
      ...ResourceValidator,
    };
  }
}
