export type { IEndpointPayload } from './IEndpointPayload';
export type { IOrganizationQualification } from './IOrganizationQualification';
export type { IPatientCommunication } from './IPatientCommunication';
export type { IPatientContact } from './IPatientContact';
export type { IPatientLink } from './IPatientLink';
export type { IPersonCommunication } from './IPersonCommunication';
export type { IPersonLink as IPersonLink } from './IPersonLink';
export type { IPractitionerQualification } from './IPractitionerQualification';
export type { IPractitionerCommunication } from './IPractitionerCommunication';
export type { IRelatedPersonCommunication } from './IRelatedPersonCommunication';
export type { IGroupCharacteristic } from './IGroupCharacteristic';
export type { IGroupMember } from './IGroupMember';
